### ISSUE TITLE
Missing includes CL and lvr2

### ISSUE THREAD

**Issue by ToniRV** [uos/mesh_tools#4]
1. By cloning manually HighFive in `ext/HightFive` I might have introduced the following problem:
When running `catkin build`, I have:
```
 #include <CL/cl2.hpp>
          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/rviz_map_plugin.dir/src/ClusterLabelPanel.cpp.o] Error 1
In file included from ...
```
and also
```
fatal error: lvr2/io/PlutoMapIO.hpp: No such file or directory
 #include <lvr2/io/PlutoMapIO.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~
```

What dependencies am I missing? Thanks

**Comment by spuetz** [comment]
Hi @ToniRV  I'll have a look today, and try to fix that issue. Thanks for reporting the bugs!

**Comment by spuetz** [comment]
Hi @ToniRV, could you check again? The bug should be fixed now.

**Comment by pedroperrusi** [comment]
Hi @spuetz, 
I still can't find the lvr2 dependency when building the package.
Are there any instructions to install it ?

**Comment by spuetz** [comment]
Hi @pedroperrusi Please see the LVR2 installation steps in the README here: https://github.com/uos/lvr2

**Comment by thanujadax** [comment]
Hi,
I'm getting the same compilation error:
```
Errors     << rviz_map_plugin:make ws/logs/rviz_map_plugin/build.make.002.log                                                                                                                          
In file included from ws/src/cleansquare_ros/utils/uos_mesh_tools/rviz_map_plugin/src/ClusterLabelTool.cpp:49:
ws/src/cleansquare_ros/utils/uos_mesh_tools/rviz_map_plugin/include/ClusterLabelTool.hpp:57:10: fatal error: CL/cl2.hpp: No such file or directory
 #include <CL/cl2.hpp>
          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/rviz_map_plugin.dir/src/ClusterLabelTool.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from ws/src/cleansquare_ros/utils/uos_mesh_tools/rviz_map_plugin/include/ClusterLabelPanel.hpp:56,
                 from ws/src/cleansquare_ros/utils/uos_mesh_tools/rviz_map_plugin/src/ClusterLabelPanel.cpp:49:
ws/src/cleansquare_ros/utils/uos_mesh_tools/rviz_map_plugin/include/ClusterLabelTool.hpp:57:10: fatal error: CL/cl2.hpp: No such file or directory
 #include <CL/cl2.hpp>
          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/rviz_map_plugin.dir/src/ClusterLabelPanel.cpp.o] Error 1
In file included from ws/build/rviz_map_plugin/rviz_map_plugin_autogen/6YEA5652QU/../../../../src/cleansquare_ros/external_modules/uos_mesh_tools/rviz_map_plugin/include/ClusterLabelPanel.hpp:56,
                 from ws/build/rviz_map_plugin/rviz_map_plugin_autogen/6YEA5652QU/moc_ClusterLabelPanel.cpp:9,
                 from ws/build/rviz_map_plugin/rviz_map_plugin_autogen/mocs_compilation.cpp:3:
/opt/enway/ws/src/cleansquare_ros/utils/uos_mesh_tools/rviz_map_plugin/include/ClusterLabelTool.hpp:57:10: fatal error: CL/cl2.hpp: No such file or directory
 #include <CL/cl2.hpp>
          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/rviz_map_plugin.dir/rviz_map_plugin_autogen/mocs_compilation.cpp.o] Error 1
In file included from ws/src/cleansquare_ros/utils/uos_mesh_tools/rviz_map_plugin/src/ClusterLabelDisplay.cpp:51:
ws/src/cleansquare_ros/utils/uos_mesh_tools/rviz_map_plugin/include/ClusterLabelTool.hpp:57:10: fatal error: CL/cl2.hpp: No such file or directory
 #include <CL/cl2.hpp>
          ^~~~~~~~~~~~
compilation terminated.
In file included from ws/src/cleansquare_ros/utils/uos_mesh_tools/rviz_map_plugin/src/MapDisplay.cpp:51:
ws/src/cleansquare_ros/utils/uos_mesh_tools/rviz_map_plugin/include/ClusterLabelTool.hpp:57:10: fatal error: CL/cl2.hpp: No such file or directory
 #include <CL/cl2.hpp>
          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/rviz_map_plugin.dir/src/ClusterLabelDisplay.cpp.o] Error 1
make[2]: *** [CMakeFiles/rviz_map_plugin.dir/src/MapDisplay.cpp.o] Error 1
make[1]: *** [CMakeFiles/rviz_map_plugin.dir/all] Error 2
make: *** [all] Error 2

```
I have installed lvr2 and also manually cloned HighFive into the expected subdirectory because `git submodule update --init --recursive` doesn't manage to clone the required recursive sub modules. The required opencl dependencies are also installed. Any idea what's wrong?
Thanks

**Comment by thanujadax** [comment]
> Hi,
> I'm getting the same compilation error:
> 
> ```
> Errors     << rviz_map_plugin:make ws/logs/rviz_map_plugin/build.make.002.log                                                                                                                          
> In file included from ws/src/cleansquare_ros/utils/uos_mesh_tools/rviz_map_plugin/src/ClusterLabelTool.cpp:49:
> ws/src/cleansquare_ros/utils/uos_mesh_tools/rviz_map_plugin/include/ClusterLabelTool.hpp:57:10: fatal error: CL/cl2.hpp: No such file or directory
>  #include <CL/cl2.hpp>
>           ^~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [CMakeFiles/rviz_map_plugin.dir/src/ClusterLabelTool.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> In file included from ws/src/cleansquare_ros/utils/uos_mesh_tools/rviz_map_plugin/include/ClusterLabelPanel.hpp:56,
>                  from ws/src/cleansquare_ros/utils/uos_mesh_tools/rviz_map_plugin/src/ClusterLabelPanel.cpp:49:
> ws/src/cleansquare_ros/utils/uos_mesh_tools/rviz_map_plugin/include/ClusterLabelTool.hpp:57:10: fatal error: CL/cl2.hpp: No such file or directory
>  #include <CL/cl2.hpp>
>           ^~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [CMakeFiles/rviz_map_plugin.dir/src/ClusterLabelPanel.cpp.o] Error 1
> In file included from ws/build/rviz_map_plugin/rviz_map_plugin_autogen/6YEA5652QU/../../../../src/cleansquare_ros/external_modules/uos_mesh_tools/rviz_map_plugin/include/ClusterLabelPanel.hpp:56,
>                  from ws/build/rviz_map_plugin/rviz_map_plugin_autogen/6YEA5652QU/moc_ClusterLabelPanel.cpp:9,
>                  from ws/build/rviz_map_plugin/rviz_map_plugin_autogen/mocs_compilation.cpp:3:
> /opt/enway/ws/src/cleansquare_ros/utils/uos_mesh_tools/rviz_map_plugin/include/ClusterLabelTool.hpp:57:10: fatal error: CL/cl2.hpp: No such file or directory
>  #include <CL/cl2.hpp>
>           ^~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [CMakeFiles/rviz_map_plugin.dir/rviz_map_plugin_autogen/mocs_compilation.cpp.o] Error 1
> In file included from ws/src/cleansquare_ros/utils/uos_mesh_tools/rviz_map_plugin/src/ClusterLabelDisplay.cpp:51:
> ws/src/cleansquare_ros/utils/uos_mesh_tools/rviz_map_plugin/include/ClusterLabelTool.hpp:57:10: fatal error: CL/cl2.hpp: No such file or directory
>  #include <CL/cl2.hpp>
>           ^~~~~~~~~~~~
> compilation terminated.
> In file included from ws/src/cleansquare_ros/utils/uos_mesh_tools/rviz_map_plugin/src/MapDisplay.cpp:51:
> ws/src/cleansquare_ros/utils/uos_mesh_tools/rviz_map_plugin/include/ClusterLabelTool.hpp:57:10: fatal error: CL/cl2.hpp: No such file or directory
>  #include <CL/cl2.hpp>
>           ^~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [CMakeFiles/rviz_map_plugin.dir/src/ClusterLabelDisplay.cpp.o] Error 1
> make[2]: *** [CMakeFiles/rviz_map_plugin.dir/src/MapDisplay.cpp.o] Error 1
> make[1]: *** [CMakeFiles/rviz_map_plugin.dir/all] Error 2
> make: *** [all] Error 2
> ```
> 
> I have installed lvr2 and also manually cloned HighFive into the expected subdirectory because `git submodule update --init --recursive` doesn't manage to clone the required recursive sub modules. The required opencl dependencies are also installed. Any idea what's wrong?
> Thanks

Found the problem. In addition to the OpenCL dependencies specified in the `lvr2` installation, I installed opencl2 headers available via synaptic (for ubuntu 18.04). Now it compiles.

**Comment by spuetz** [comment]
https://packages.ubuntu.com/bionic/opencl-clhpp-headers is required. I'll add this to the dependencies soon. Thank you for reporting the bug.

**Comment by spuetz** [comment]
Just run `rosdep install --from-paths src --ignore-src -r -y` in the workspace folder.

**Comment by xmfcx** [comment]
When I issue the command, I get following:
```
rosdep install --from-paths src --ignore-src
executing command [sudo -H apt-get install ros-melodic-lvr2]
[sudo] password for mfc: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-melodic-lvr2
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install ros-melodic-lvr2] failed
```

**Comment by roboticsai** [comment]
It is working for me.
